### ISSUE TITLE
Norwegian Sector Alarm

### ISSUE THREAD

**Issue by bohtho** [perbrage/node-red-contrib-sectoralarm#1]
Would this work on the Norwegian Sector Alarm site too, and if not where in the code do I edit which site to crawl ?

**Comment by bohtho** [comment]
Forget it. I have yet to try the nodes in my node-red but I can log into both "minasidor.sectoralarm.se" og "minside.sectoralarm.no" with the same (Norwegian) logon so I guess it will work anyhow.

**Comment by perbrage** [comment]
Thats is good to know! Maybe I should update the readme that it works for several countries and not just in Sweden.

**Comment by bohtho** [comment]
Tested and works fine in node-red for Norwegian Sector customers as well:)

**Comment by perbrage** [comment]
That is nice. It also seems Denmark, Finland and Ireland are using very similar user pages. Spain does not seem to have user pages. I can try to re-direct the package to the various countries and see if it works.
