### ISSUE TITLE
Updated node-red addon as well?

### ISSUE THREAD

**Issue by bohtho** [perbrage/node-red-contrib-sectoralarm#10]
I noticed you rebuilt and updated your main library for sector alarm. Will this trickle into the node-red contrib updates as well?

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by perbrage** [comment]
Yes it will, I have just not had the time to do it yet. Will try to get it fixed in the upcoming days

**Comment by perbrage** [comment]
Hi,

Sorry for the long wait. Package updated. 1.3.4 has new general library
