### ISSUE TITLE
Secure Connection?

### ISSUE THREAD

**Issue by thornerjohan** [perbrage/node-red-contrib-sectoralarm#14]
Hello. 
How is the communication between homebridge/this plugin and Sectoralarm?
Is data sent in the open or is it encrypted in any way. 
I am primarily thinking about my login details. 

Br Johan

**Comment by perbrage** [comment]
Hi,

The nodered package is using my general sectoralarm library (another repo of mine). In there you can verify at line 23 in client.js that communication is done over https, using the port 443 specified at line 17 in the same file. 

The connection is secure!
