### ISSUE TITLE
Error status persistent

### ISSUE THREAD

**Issue by bohtho** [perbrage/node-red-contrib-sectoralarm#3]
The yellow error status under the node is persistent even after there’s no error anymore. And if my node-red setup registers the state of error it never gets a normal “check” status again because “check” apparently only outputs and checks against last status before the error.

**Comment by perbrage** [comment]
Yes, I have noticed this as well. And I actually saw one of the errors it produced, which led to me first starting to sort out an issue in the general library. Haven't had time to update the node-red node yet.

Thinking about doing something about the error messages in general as well, when I fint the time.

**Comment by perbrage** [comment]
Problem should now be fixed in the last release. Try it out.

**Comment by bohtho** [comment]
Works excellent!

**Comment by JohanFalk84** [comment]
Hello I´m new in this node red. 
How do i do for installing it and config in node red.

**Comment by perbrage** [comment]
Instructions for installing node-red can be found here
https://nodered.org/docs/getting-started/installation

Upgrading the installation in case you are on a Raspberry PI can be found here
https://nodered.org/docs/hardware/raspberrypi

Installing this and other nodes can be done through UI or npm. Instructions can be found here
https://nodered.org/docs/getting-started/adding-nodes

Cheers
