### ISSUE TITLE
Flows stopped due to missing node types.

### ISSUE THREAD

**Issue by frankis78** [perbrage/node-red-contrib-sectoralarm#4]
Hi, i cannot get this to work.
In node red i get this error:
Flows stopped due to missing node types.
-sectoralarm-site

And in putty i see this error
[warn] [node-red-contrib-sectoralarm/site] SyntaxError: Unexpected token = (line:1)

**Comment by bohtho** [comment]
See last few comments in issue #2. This could also be a permission issue by how node-red is installed. I had this problem in the Openhabian install of node-red.

**Comment by frankis78** [comment]
Can someone check line one in the sectoralarm-site.js file?
I am not an expert in this, but i get an error on this file.
![2018-04-25_2355](https://user-images.githubusercontent.com/26933092/39275081-40ac2e50-48e4-11e8-9778-5e1b12fa0dc4.png)

**Comment by frankis78** [comment]
Hi 
I started from scratch again, and installed the raspbian stretch again, with a fresh node-red, and i still get this error

Flows stopped due to missing node types.
sectoralarm-site

**Comment by perbrage** [comment]
That seems odd, the first line should not look like that. Check the code here on master branch. It should just require sectoralarm. I made a general library named sectoralarm for people not using node-red, which is a dependency for this node red contrib.

Did you change that line yourself?

What version of nodejs and npm do you use?

Can you see that the dependency is installed under nodemodules?

**Comment by frankis78** [comment]
That first line was some error i got on previous install.
Now i made a fresh install, and all is up to date with nodejs and npm (Sudo apt-get update)
and it is running on a raspberry pi 3.
So first thing i did , is to install the plugin, and click deploy, and then i get this error in node red
Flows stopped due to missing node types.
sectoralarm-site
I can see that it is installed correctly, and it also have the dependency module under the same folder in .
I also tried to change site to sectoralarm-site, but it doesent make any difference.

**Comment by perbrage** [comment]
Hi!

I just put out a new version (1.1.4) which updates the dependency to the general library sectoralarm, where I have made some bug fixing, and added custom errors that can include the original error from communicating with sector alarm.

The node now also have some general logging, that should turn up in the console log (or depending where you have configured it to end up). Errors should also turn up in the debug log in the UI.

You also have an error output, and the node-red error catcher to further try to investigate your issues.

I've also updated the name discrepancy that was mentioned earlier in this thread, unsure if that means anything at all, but better to be consistent.

I really think you should remove all files and any remnants of this node in your flows after uninstalling this node, then reinstall the node. If you are using projects, don't forget to use the UI to install the node in your project as well.

Happy problem hunting, and let us know if you find any bugs or issues I can help with.

**Comment by frankis78** [comment]
Hi Per
I tested it now, and installed it again.
It seems like i still have the same problem, but now i get the error in the debug window
"Credential type 'sectoralarm-site' is not registered"
Does this tell you anything?
![2018-04-29_2341](https://user-images.githubusercontent.com/26933092/39411275-3d265956-4c07-11e8-9b24-5e1ba5dea960.png)

**Comment by perbrage** [comment]
It might be that you credentials file where all sensitive configuration is stored encrypted for your flows is corrupt. Either your key doesn't match anymore, or the file is pointing to an older version.
In either case, reinstalling node-red or upgrading nodes won't help since this is user data.

Try this:

Under your node-red user's home directory, find the .node-red directory. You should find 2 files named something like. flows_YOURCOMPUTERNAME.json and flows_YOURCOMPUTERNAME_cred.json. 
(If you are using projects, those files will be found in a subfolder to .node-red/projects/<projectname>)

Back up both files and then delete them and then restart node-red. You should now have a clean node-red with no flows. 

Drag the node onto a new flow, double click it to configure it properly before deploying the flows.

**Comment by frankis78** [comment]
I removed all flows and cred  files, but for some reason it still complains about a syntax error.
This is how it looks like when i installed the sector alarm plugin again.
![2018-04-30_1645](https://user-images.githubusercontent.com/26933092/39433398-0d915094-4c96-11e8-9949-a5f14ffe680f.png)

**Comment by perbrage** [comment]
Your nodejs version is really old, please upgrade to 8+ at least

**Comment by frankis78** [comment]
This Node.js is the newest one that is following the package of raspbian stretch.
Do i need to uninstall it and install the latest one? If so, i read that apt-get will not work anymore, because it will be manually installed, and not a part of the package manager .
Sorry, im not that good with Linux:)

**Comment by perbrage** [comment]
Yeah, the NodeJs that is packaged with raspbian is quite old. Node-Red made a script to upgrade NodeJs and NodeRed at the same time, and you can find more information about it here https://nodered.org/docs/hardware/raspberrypi

Basically, you just do a update-nodejs-and-nodered using your pi user. At some point in time I had to run in twice to get through all steps.

**Comment by frankis78** [comment]
I can confirm that it works now, with updated nodejs. That was the problem all the time.
Thanks:)

**Comment by bohtho** [comment]
Good to know that was it (may have been my issue as well although I went about it in more ways).

**Comment by frankis78** [comment]
Can you give some examples what topic we should use on a publish MQTT, from the output sector node
Like sector/currentStatus/armedStatus
I figured the input node (check, status, arm etc), but not the output node, what Topic i should use for different statuses
