### ISSUE TITLE
Changed API ?

### ISSUE THREAD

**Issue by bohtho** [perbrage/node-red-contrib-sectoralarm#5]
Should maybe be directed to the nodejs library, but when disarming I now get the error: 

> code: "ERR_INVALID_CODE"
> action: "DISARM"
> message: "Invalid code, could not act upon alarm of the site"

**Comment by perbrage** [comment]
I ran all automated tests in the general library and they all pass!
Also, I ran manual test of actually disarming and then arming, which also pass!

Can you check if you still are having issues?

From your paste I can see that the original error is still missing though. My intent was that would be shown as well being part of the error object. Something to fix later on.

**Comment by perbrage** [comment]
As I have not heard more of your problem, I took the liberty to update both the general library and the node to hopefully include more information of the original error. 

Let me know how it works out for you.

Use version 1.1.5

**Comment by bohtho** [comment]
Been away, but seems the error and what seemed like an API change vanished for me. Anyhow it is good to get the clearer errors.
