### ISSUE TITLE
Doorlock status

### ISSUE THREAD

**Issue by frankis78** [perbrage/node-red-contrib-sectoralarm#6]
The plugin works great:)
I was just wondering if it is possible to retrieve the door lock status, when you have a Yale Doorman doorlock attached to the alarm system.
Currently we get status armed, armed-home, and disarmed, but it would be also nice to have locked and unlocked status for the door lock.

**Comment by perbrage** [comment]
As I don't have that lock, and have no idea on how the responses are from from SectorAlarm with locked/unlocked I can't really implement it. If you could provide me with the json responses I could have a look at it.

**Comment by frankis78** [comment]
I have another house with Verisure alaralm and same door lock, which is much the same as sector, and there i control it simply sending lock and unlock.
I control it this way.
$ mosquitto_pub -t 'verisure/doorLock/YourLock/set' -m 'unlock'
$ mosquitto_pub -t 'verisure/doorLock/YourLock/set' -m 'lock'

Regarding the Json response, can you quickly tell how i can trace it, and i will lock and unlock the door to get the responce.
Thanks

**Comment by frankis78** [comment]
I think i found some info:

POST
https://minside.sectoralarm.no/Locks/Lock
https://minside.sectoralarm.no/Locks/Unlock

Json
DisarmCode	"your personal code"
id	"the alarm system id"
LockSerial	"some serial from lock"

Status
<span ng-if="(lock.Status == 'lock' || lock.Status == 'unlock') &amp;&amp; !lock.isUpdateing &amp;&amp; !system.Locks.loading" class="ng-binding ng-scope" style="">er ulåst</span>
<span ng-if="(lock.Status == 'lock' || lock.Status == 'unlock') &amp;&amp; !lock.isUpdateing &amp;&amp; !system.Locks.loading" class="ng-binding ng-scope" style="">er låst</span>

**Comment by perbrage** [comment]
Adding this functionality is possible, but as I said before, I can't do it without having a lock to try it out. If anyone have a lock and can do some development, then the code needs to end up in my general library first, found here: https://github.com/perbrage/sectoralarm

Leaving this issue open for the time being.

**Comment by perbrage** [comment]
As this has been implemented I am now closing the issue.
