### ISSUE TITLE
ERR_PARSING_ERROR

### ISSUE THREAD

**Issue by phralh** [perbrage/node-red-contrib-sectoralarm#7]
I'm new to node-red. Fresh install of node-red on raspberry pi 3, and getting ERR_PERSING_ERROR for 'status', 'check' and 'history'. 'arm', 'partialArm' and 'disarm' gives me ERR_INVALID_CODE, even though I even set a new code with sector alarm. Sectoralarm seems to connect just fine. 

object
code: "ERR_PARSING_ERROR"
message: "Could not parse the response received from Sector Alarm. See innerError for more details"
stack: string
SectorAlarmError: Could not parse the response received from Sector Alarm. See innerError for more details
    at /home/pi/.node-red/node_modules/node-red-contrib-sectoralarm/node_modules/sectoralarm/lib/parser.js:77:24
    at tryCallTwo (/home/pi/.node-red/node_modules/node-red-contrib-sectoralarm/node_modules/sectoralarm/node_modules/promise/lib/core.js:45:5)
    at doResolve (/home/pi/.node-red/node_modules/node-red-contrib-sectoralarm/node_modules/sectoralarm/node_modules/promise/lib/core.js:200:13)
    at new Promise (/home/pi/.node-red/node_modules/node-red-contrib-sectoralarm/node_modules/sectoralarm/node_modules/promise/lib/core.js:66:3)
    at Parser.transformHistoryToOutput (/home/pi/.node-red/node_modules/node-red-contrib-sectoralarm/node_modules/sectoralarm/lib/parser.js:48:16)
    at Promise.resolve.then.then.json (/home/pi/.node-red/node_modules/node-red-contrib-sectoralarm/node_modules/sectoralarm/lib/site.js:39:34)
    at <anonymous>
    at process._tickCallback (intern...
originalError: object
message: "Unexpected token < in JSON at position 0"
stack: string
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /home/pi/.node-red/node_modules/node-red-contrib-sectoralarm/node_modules/sectoralarm/lib/parser.js:72:45
    at tryCallTwo (/home/pi/.node-red/node_modules/node-red-contrib-sectoralarm/node_modules/sectoralarm/node_modules/promise/lib/core.js:45:5)
    at doResolve (/home/pi/.node-red/node_modules/node-red-contrib-sectoralarm/node_modules/sectoralarm/node_modules/promise/lib/core.js:200:13)
    at new Promise (/home/pi/.node-red/node_modules/node-red-contrib-sectoralarm/node_modules/sectoralarm/node_modules/promise/lib/core.js:66:3)
    at Parser.transformHistoryToOutput (/home/pi/.node-red/node_modules/node-red-contrib-sectoralarm/node_modules/sectoralarm/lib/parser.js:48:16)
    at Promise.resolve.then.then.json (/home/pi/.node-red/node_modules/node-red-contrib-sectoralarm/node_modules/sectoralarm/lib/site.js:39:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick....

**Comment by perbrage** [comment]
Hi

I am seeing this issue at times, and I believe that there is a response from sector alarm that is not handled properly, but I can not reproduce the issue.

Does this error occur once in awhile or all the time?

**Comment by bohtho** [comment]
Now I a get parsing error on everything. Have Sector upgraded their code/api?

**Comment by bingete** [comment]
Same. I get parsing error on everything

**Comment by perbrage** [comment]
I will check within the next couple of days to see if there are any changes that needs to be resolved, or if this is just a temporary sector alarm glitch!

**Comment by perbrage** [comment]
Changes to the API is confirmed and the status and temperatures has already been resolved. There are however additional changes to the status of locks and acting on locks that needs to be resolved. I will keep you updated.

**Comment by perbrage** [comment]
Hi,

There is now a new version (1.3.2) with resolutions to the problems. Please check it out and report any problems you might have. 

Thanks!

**Comment by eiriktakle** [comment]
I'm still getting ERR_PARSING_ERROR:

{"code":"ERR_PARSING_ERROR","message":"Could not parse the response received from Sector Alarm. See innerError for more details","stack":"SectorAlarmError: Could not parse the response received from Sector Alarm. See innerError for more details\n    at /home/pi/.node-red/node_modules/sectoralarm/lib/parser.js:123:31\n    at tryCallTwo (/home/pi/.node-red/node_modules/promise/lib/core.js:45:5)\n    at doResolve (/home/pi/.node-red/node_modules/promise/lib/core.js:200:13)\n    at new Promise (/home/pi/.node-red/node_modules/promise/lib/core.js:66:3)\n    at Parser.transformStatusToOutput (/home/pi/.node-red/node_modules/sectoralarm/lib/parser.js:96:16)\n    at Promise.resolve.then.then.status (/home/pi/.node-red/node_modules/sectoralarm/lib/site.js:42:36)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","originalError":{"message":"Cannot read property 'PanelId' of undefined","stack":"TypeError: Cannot read property 'PanelId' of undefined\n    at Object.siteId (/home/pi/.node-red/node_modules/sectoralarm/lib/parser.js:100:40)\n    at module.exports.applySchema (/home/pi/.node-red/node_modules/json-mapper/json-mapper.js:69:34)\n    at /home/pi/.node-red/node_modules/json-mapper/json-mapper.js:99:16\n    at /home/pi/.node-red/node_modules/sectoralarm/lib/parser.js:118:30\n    at tryCallTwo (/home/pi/.node-red/node_modules/promise/lib/core.js:45:5)\n    at doResolve (/home/pi/.node-red/node_modules/promise/lib/core.js:200:13)\n    at new Promise (/home/pi/.node-red/node_modules/promise/lib/core.js:66:3)\n    at Parser.transformStatusToOutput (/home/pi/.node-red/node_modules/sectoralarm/lib/parser.js:96:16)\n    at Promise.resolve.then.then.status (/home/pi/.node-red/node_modules/sectoralarm/lib/site.js:42:36)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}}

**Comment by perbrage** [comment]
What action you use to producing this error? I've got response that "info" action might result in this error, which also might depend on the configuration of the alarm, eg. having or or not having temp sensors for example.

Can you give me some more info?

**Comment by eiriktakle** [comment]
I'm using inject-nodes for "status" and "check". They are injected as
strings. Check is repeated every 2 seconds, and status is rarely used, but
gives the same error.

I have two motion detectors with temperature metering, no door lock, no
annex.





fre. 12. apr. 2019, 19:22 skrev Per Brage <notifications@github.com>:

**Comment by eiriktakle** [comment]
"Temperatures" and "history" are working as they should..

fre. 12. apr. 2019, 20:19 skrev Eirik Takle <eiriktakle@gmail.com>:

**Comment by bohtho** [comment]
Version 1.3.2 seems to work ok for me. I have no annexe, no temperature sensors, no door locks though.

**Comment by bohtho** [comment]
The last week I started to get the same parsing error ....

**Comment by perbrage** [comment]
Updated the general library as Sector Alarm now requires a new version. Issue is not resolved in the node-red lib yet. Update coming

**Comment by perbrage** [comment]
Update to version 1.3.3 and give it a spin

**Comment by phralh** [comment]
I too started having issues with Status last week. Updated to 1.3.3 and status no longer gives parsing error, so seems to work fine now! 

By the way, the original issue in this thread was resolved and the error was on my side and caused by wrong Site ID in the config.

**Comment by bohtho** [comment]
Smooth as silk again!
