### ISSUE TITLE
Site Id / Panel Id for Finnish Sector Alarm site

### ISSUE THREAD

**Issue by Tsepatek** [perbrage/node-red-contrib-sectoralarm#9]
Hi,
Could someone help me with the Site ID
What should be configured to Site ID in the node?
My site for the Finnish Sector Alarm is like https://omatsivut.sectoralarm.fi/#!/systems/05088888.

Error I get is "message: "Cannot read property 'PanelId' of undefined""

**Comment by Tsepatek** [comment]
Hi,
This might be solved. You only need to set the site ID to omatsivut.sectoralarm.fi

**Comment by Tsepatek** [comment]
Hi,
I was able to get this working yesterday with Site Id omatsivut.sectoralarm.fi, but today it is not working anymore.

I can connect to Sector Alarm with my credentials and Sector Alarm node says "connected", but when I try to send "status" payload I get the errors below. Please, help?

SectorAlarmError: Could not parse the response received from Sector Alarm. See innerError for more details    at /home/pi/.node-red/node_modules/sectoralarm/lib/parser.js:123:31    at tryCallTwo (/home/pi/.node-red/node_modules/promise/lib/core.js:45:5)    at doResolve (/home/pi/.node-red/node_modules/promise/lib/core.js:200:13)    at new Promise (/home/pi/.node-red/node_modules/promise/lib/core.js:66:3)    at Parser.transformStatusToOutput (/home/pi/.node-red/node_modules/sectoralarm/lib/parser.js:96:16)    at Promise.resolve.then.then.status (/home/pi/.node-red/node_modules/sectoralarm/lib/site.js:42:36)    at <anonymous>    at process._tickCallback (internal/process/next_tick.js:188:7)

Cannot read property 'PanelId' of undefined
TypeError: Cannot read property 'PanelId' of undefined
    at Object.siteId (/home/pi/.node-red/node_modules/sectoralarm/lib/parser.js:100:40)
    at module.exports.applySchema (/home/pi/.node-red/node_modules/json-mapper/json-mapper.js:69:34)
    at /home/pi/.node-red/node_modules/json-mapper/json-mapper.js:99:16
    at /home/pi/.node-red/node_modules/sectoralarm/lib/parser.js:118:30
    at tryCallTwo (/home/pi/.node-red/node_modules/promise/lib/core.js:45:5)
    at doResolve (/home/pi/.node-red/node_modules/promise/lib/core.js:200:13)
    at new Promise (/home/pi/.node-red/node_modules/promise/lib/core.js:66:3)
    at Parser.transformStatusToOutput (/home/pi/.node-red/node_modules/sectoralarm/lib/parser.js:96:16)
    at Promise.resolve.then.then.status (/home/pi/.node-red/node_modules/sectoralarm/lib/site.js:42:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7

**Comment by perbrage** [comment]
Hi!

PanelId and SiteId is the same thing. Looking at your url you posted your siteId is 05088888

BR 
Per

**Comment by Tsepatek** [comment]
So, is my url correct. Do I need https:// there or what is the correct Site Id setting?
https://omatsivut.sectoralarm.fi/#!/systems/05088888 is this correct?

**Comment by perbrage** [comment]
As I said, your site id is 05088888, and you enter that as the site id in your configuration

You don’t use any url

**Comment by Tsepatek** [comment]
![image](https://user-images.githubusercontent.com/50211168/58087846-135d4280-7bca-11e9-9349-6b672b287d40.png)

I cannot get this to work again. Yesterday I was able to get the status (see the picture). Now I only get parser errors.

**Comment by perbrage** [comment]
Try two things!

1) In a browser, try to login with your username and password on the international website at mypagesapi.sectoralarm.net by surfing to it. If that works you should be able to use this package.

2) Make sure you are using the latest version available since the last update resolved changes in the api, which also resulted in parsing errors. Restart node-red  after upgrading

//Per

**Comment by Tsepatek** [comment]
Hi,
This is quite strange. now I tried to send payload "history" and everything works fine with site ID 05088888.
Here is the result [{"time":"2019-05-21 15:52:51","action":"disarmed","user":"Koodi"}]. 
Also "temperatures" is working fine.
But if I send "status" or "info" or "check" I get 

code: "ERR_PARSING_ERROR"
message: "Could not parse the response received from Sector Alarm. See innerError for more details"
stack: "SectorAlarmError: Could not parse the response received from Sector Alarm. See innerError for more details↵ at /home/pi/.node-red/node_modules/sectoralarm/lib/parser.js:123:31↵ at tryCallTwo (/home/pi/.node-red/node_modules/promise/lib/core.js:45:5)↵ at doResolve (/home/pi/.node-red/node_modules/promise/lib/core.js:200:13)↵ at new Promise (/home/pi/.node-red/node_modules/promise/lib/core.js:66:3)↵ at Parser.transformStatusToOutput (/home/pi/.node-red/node_modules/sectoralarm/lib/parser.js:96:16)↵ at Promise.resolve.then.then.status (/home/pi/.node-red/node_modules/sectoralarm/lib/site.js:42:36)↵ at <anonymous>↵ at process._tickCallback (internal/process/next_tick.js:188:7)"

**Comment by perbrage** [comment]
To me it seems you are either using an old version, or sector alarm has changed something in their api again, which means this package needs an update and version bump

**Comment by perbrage** [comment]
Please make sure you are using v1.3.2 and have restarted node-red after update! If that doesn’t help you need to wait until I have fixed the issue and published a new version!

**Comment by Tsepatek** [comment]
Hi,
I think it was some kind of temporary problem in Sector Alarm's end. Now everything is working smoothly.
Maybe you can now add .fi site to confirmed - Yes.

Thank you for the help.

**Comment by perbrage** [comment]
Closing this as it has been resolved
